spring:
  profiles:
    active:
    - dev #当前使用的环境
---
server:
  port: 6001
content: "dev content 刷新了了了了了"
spring:
  profiles: dev #开发环境
  application:
    name: config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://yys.server01.com:1001/eureka/
---
server:
  port: 6002
content: "test content 没有刷新"
spring:
  profiles: test #测试环境
  application:
    name: config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://yys.server01.com:1001/eureka/
